# Generated by Django 3.1.4 on 2020-12-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='phno',
            field=models.PositiveIntegerField(max_length=10, null=True, unique=True),
        ),
    ]
